UNSIGNED INT16 KQADC,AN0, AN1;
UNSIGNED INT8 CONFIG_FUN=0;
UNSIGNED INT8 VT=0, KYTU=0;// KYTU[30], 
UNSIGNED INT8 ID_DEVICE_NHAN,TT_DEVICE_NHAN;
UNSIGNED INT8 ID_GATEWAY[6] = {5,7,3,5,4,5};
UNSIGNED INT8 ID_NODE[4] = {0,0,0,0};
UNSIGNED INT8 LEN_PACKAGES = 0;
UNSIGNED INT32 ID_GW_NHAN, ID_GW_NUMBER;
UNSIGNED INT16 ID_NODE_NHAN, ID_NODE_NUMBER;
UNSIGNED INT8 LENHDIEUKHIEN =0, DODAI_DATA_NHAN =0;
INT1 TTNHAN = 0, TT_CONFIG=0, TT_CONTROL=0,TT_CONFIG_DONE=0, TT_FUN=0, TT_STT=0;

CHAR *ID_NODE_CHAR[]= "0000";
CHAR *ID_GATEWAY_CHAR[]= "000000";
CHAR KYTUCHAR[30]="HIHI";
//CHAR *DATA_NHANDUOC[]={"IDGW","IDNODE","COMMAN","DATA"};
CHAR *TEMP_CHAR[]="00"; 
//CHAR *TEMP_CHAR3[]="0000"; 

